apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
   name: nfs-prov-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: aws-eks
roleRef:
   kind: ClusterRole
   name: cluster-admin
   apiGroup: rbac.authorization.k8s.io 
