apiVersion: v1
kind: Service
metadata:
    name: sql
    labels:
       sel: sql
spec:
   selector:
       sel: sql
   clusterIP: None
   ports:
     - port: 3306
       targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
     name: sql
spec:
   selector:
     matchLabels:
       sel: sql
   strategy: 
          type: Recreate
       
   template:
       metadata:
          name: sql
          labels: 
              sel: sql
       spec:
         containers:
             - name: sql
               image: mysql:5.7
               env:
                 - name: MYSQL_ROOT_PASSWORD
                   valueFrom:
                        secretKeyRef: 
                            name: mysecure
                            key: rootpass
                 - name: MYSQL_USER
                   value: aditi
                 - name: MYSQL_PASSWORD
                   valueFrom:
                        secretKeyRef:
                              name: mysecure
                              key: userpass
                 - name: MYSQL_DATABASE
                   value: sqldb
               volumeMounts:
                   - name: sql-vol
                     mountPath: /var/lib/mysql
         volumes:
             - name: sql-vol
               persistentVolumeClaim:
                      claimName: efs-mysql