apiVersion: v1
kind: Service
metadata:
    name: wp
    labels:
       sel: wp
spec:
   selector:
       sel: wp
   type: LoadBalancer
   ports:
     - port: 80
       targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
     name: wp
spec:
   selector:
     matchLabels:
       sel: wp
   strategy: 
          type: Recreate
   template:
       metadata:
          name: wp
          labels: 
              sel: wp
       spec:
         containers:
             - name: wp
               image: wordpress:5.1.1-php7.3-apache
               env:
                 - name: WORDPRESS_DB_HOST
                   value: sql
                 - name: WORDPRESS_DB_USER
                   value: root
                 - name: WORDPRESS_DB_PASSWORD
                   valueFrom:
                        secretKeyRef:
                              name: mysecure
                              key: rootpass
                 - name: WORDPRESS_DB_NAME
                   value: sqldb
               volumeMounts:
                  - name: wp-vol
                    mountPath: /var/www/html
         volumes:
             - name: wp-vol
               persistentVolumeClaim:
                      claimName: efs-wordpress